name: Release Gist Web
run-name: Release gist-web

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.GIST_WEB_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GIST_WEB_AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: 'gist-code'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Version name
        shell: bash
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION"

          AWS_DEST="web/$RELEASE_VERSION"
          echo "AWS_DEST=$AWS_DEST" >> $GITHUB_ENV
          echo "AWS_DEST=$AWS_DEST"
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ env.AWS_BUCKET }}
          source_dir: 'dist'          
          destination_dir: ${{ env.AWS_DEST }}
          endpoint: 'ams3.digitaloceanspaces.com'
