name: Release Gist Web
run-name: Release gist-web

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.GIST_WEB_AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GIST_WEB_AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: 'gist-code'
      CLOUDFLARE_ACCESS_TOKEN: ${{ secrets.CLOUDFLARE_ACCESS_TOKEN }}
      CLOUDFLARE_ZONE_ID: 3310bc68d22035edbc12d5d4a4fd278c
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install npm 11.5.1+ for OIDC support
        run: npm install -g npm@latest

      - name: Build
        shell: bash
        run: |
          npm install
          npm run build:prod

      - name: Set test version
        run: npm version 0.0.0-test-oidc --no-git-tag-version

      - name: Publish to NPM
        run: npm publish --tag test-oidc
