name: Trigger a Gist Web Release
run-name: Release gist-web

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version change'
        required: true
        options:
          - 'patch'
          - 'minor'
          - 'major'
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: develop
        token: ${{ secrets.SRE_GHACTIONS_TOKEN }}
    - name: Increment package.json version
      uses: 'phips28/gh-action-bump-version@master'
      env:
        GITHUB_TOKEN: ${{ secrets.SRE_GHACTIONS_TOKEN }}
      with:
        version-type: '${{ inputs.version }}'        
        skip-tag: 'true'
    - name: Extract new npm version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1        
    - name: Release to master
      shell: bash
      env:
        GIT_AUTH_TOKEN: ${{ secrets.SRE_GHACTIONS_TOKEN }}
      run: |
        git pull origin develop
        git checkout master
        git merge develop
        git push origin master
        git tag ${{ steps.package-version.outputs.current-version }}
        git push origin ${{ steps.package-version.outputs.current-version }}

        